services:
  app.handler.cache_manager_service:
    class: Sensio\Bundle\CacheBundle\Service\CacheHandler
    arguments:  ['%kernel.cache_dir%']
    tags:
      - { name: kernel.event_listener, event: kernel.request }
